In [3]:
import pandas as pd
import numpy as np
from geotext import GeoText
import re

df = pd.read_csv('rappler_scraping1.csv')
confirmed = pd.read_csv('rappler_scraping_confirmed_nCov.csv')

df = df.append(confirmed).reset_index()

In [4]:
df.head()

,index,Unnamed: 0,source_id,date,category,title,author,text
0,0,0,249700,"January 19, 2020",Other Sports,'No holidays': Hidilyn Diaz on track for Tokyo...,Beatrice Go,Hidilyn Diaz wants to boost her world ranking ...
1,1,1,249701,"January 19, 2020",Relationships,[Two Pronged] A barkada that pries too much,Dr. Margarita Holmes and Jeremy Baer,What happens if your friends ask too much abou...
2,2,2,249702,"January 19, 2020",Middle East,Almost 400 wounded in Lebanon clashes – rescuers,Agence France-Presse,"The toll on Saturday, January 18, is the heavi..."
3,3,3,249703,"January 19, 2020",Business,Founder of South Korean retail giant Lotte die...,Agence France-Presse,Shin Kyuk-ho is the founder of one of South Ko...
4,4,4,249704,"January 20, 2020",Move.PH,Artivism gives face to Iloilo’s vulnerable pub...,Rhick Lars Vladimer Albay,As rapid growth pushes local vendors to the fr...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1087 entries, 0 to 1086
Data columns (total 8 columns):
index         1087 non-null int64
Unnamed: 0    1087 non-null int64
source_id     1087 non-null int64
date          1087 non-null object
category      1087 non-null object
title         1087 non-null object
author        1087 non-null object
text          1087 non-null object
dtypes: int64(3), object(5)
memory usage: 68.1+ KB

In [6]:
df['ncov'] = df['title'].str.find(r'coronavirus')

In [7]:
df_ncov = df[df['ncov']>0]

In [8]:
df_ncov.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95 entries, 38 to 1086
Data columns (total 9 columns):
index         95 non-null int64
Unnamed: 0    95 non-null int64
source_id     95 non-null int64
date          95 non-null object
category      95 non-null object
title         95 non-null object
author        95 non-null object
text          95 non-null object
ncov          95 non-null int64
dtypes: int64(4), object(5)
memory usage: 7.4+ KB

In [9]:
df_ncov.columns

Index(['index', 'Unnamed: 0', 'source_id', 'date', 'category', 'title',
       'author', 'text', 'ncov'],
      dtype='object')

In [10]:
df1 = df_ncov[['source_id', 'date', 'category', 'title', 'author', 'text']].reset_index()
df1['places'] = df1['title'].apply(lambda x: GeoText(x))
df1['cities'] = df1['places'].apply(lambda x: list(x.cities))
df1.head()

,index,source_id,date,category,title,author,text,places,cities
0,38,249739,"January 20, 2020",Life & Health,What is coronavirus? New disease spreading in ...,Agence France-Presse,An expert says the fact that the virus had spr...,<geotext.geotext.GeoText object at 0x000002193...,[Asia]
1,130,249832,"January 21, 2020",Philippines,DOH probes suspected case of novel coronavirus...,Janella Paris,(3rd UPDATE) Health Secretary Francisco Duque ...,<geotext.geotext.GeoText object at 0x000002193...,[Cebu City]
2,164,249868,"January 21, 2020",Rappler IQ,Novel coronavirus or 2019-nCoV: What we know s...,Janella Paris,(2nd UPDATE) The World Health Organization has...,<geotext.geotext.GeoText object at 0x000002193...,[]
3,207,249914,"January 22, 2020",Philippines,Duque: Still many blindspots in ‘novel coronav...,Janella Paris,Duque says being infected with a coronavirus i...,<geotext.geotext.GeoText object at 0x000002193...,[]
4,286,249996,"January 23, 2020",Philippines,"Stay vigilant vs novel coronavirus, PHO-Aklan ...",Boy Ryan B. Zabal,"Kalibo gets international flights daily, mostl...",<geotext.geotext.GeoText object at 0x000002193...,[]

In [11]:
near_num = r"(?:[a-zA-Z'-]+[^a-zA-Z'-]+){0,3}[0-9](?:[^a-zA-Z'-]+[a-zA-Z'-]+){0,3}"

df1['near_num'] = df['text'].apply(lambda x: re.findall(near_num, x))

In [12]:
df1

,index,source_id,date,category,title,author,text,places,cities,near_num
0,38,249739,"January 20, 2020",Life & Health,What is coronavirus? New disease spreading in ...,Agence France-Presse,An expert says the fact that the virus had spr...,<geotext.geotext.GeoText object at 0x000002193...,[Asia],[the penultimate Tokyo 2020 Olympics qualifier...
1,130,249832,"January 21, 2020",Philippines,DOH probes suspected case of novel coronavirus...,Janella Paris,(3rd UPDATE) Health Secretary Francisco Duque ...,<geotext.geotext.GeoText object at 0x000002193...,[Cebu City],"[A banker of 37 years who worked, in 3 contine..."
2,164,249868,"January 21, 2020",Rappler IQ,Novel coronavirus or 2019-nCoV: What we know s...,Janella Paris,(2nd UPDATE) The World Health Organization has...,<geotext.geotext.GeoText object at 0x000002193...,[],"[on Saturday, January 18, is the heaviest, the..."
3,207,249914,"January 22, 2020",Philippines,Duque: Still many blindspots in ‘novel coronav...,Janella Paris,Duque says being infected with a coronavirus i...,<geotext.geotext.GeoText object at 0x000002193...,[],"[photo on July 28, 2015, shows Lotte group, th..."
4,286,249996,"January 23, 2020",Philippines,"Stay vigilant vs novel coronavirus, PHO-Aklan ...",Boy Ryan B. Zabal,"Kalibo gets international flights daily, mostl...",<geotext.geotext.GeoText object at 0x000002193...,[],"[Viejo. In December 2019, Buenavista and a, fi..."
...,...,...,...,...,...,...,...,...,...,...
90,1066,250802,"February 02, 2020",Business,Cebu Pacific alerts fellow passengers of Phili...,Rappler.com,The woman and man found to have the novel coro...,<geotext.geotext.GeoText object at 0x000002193...,[],[was born January 20. Screenshot from Instagra...
91,1075,250813,"February 02, 2020",Rappler IQ,Beyond coronavirus: Things to know about China...,Jodesz Gavilan,"Wuhan City, the biggest in Hubei province, is ...",<geotext.geotext.GeoText object at 0x000002193...,[],"[on Sunday, January 19, that it will, Bordeaux..."
92,1078,250816,"February 02, 2020",Other Sports,Tokyo to 'strengthen testing' for coronavirus ...,Agence France-Presse,Japan has warned citizens against non-essentia...,<geotext.geotext.GeoText object at 0x000002193...,[Tokyo],"[being inside the 14, Taal Volcano) “Noong 196..."
93,1084,186633,"January 30, 2020",Philippines,Philippines confirms 1st case of novel coronav...,Janelle Paris,(3rd UPDATE) The Philippines' first 2019-nCoV ...,<geotext.geotext.GeoText object at 0x000002193...,[],"[triumph in the 2019, -20 Governors' Cup on, M..."
94,1086,251003,"February 05, 2020",Philippines,Philippines confirms 3rd case of novel coronav...,Janella Paris,(6th UPDATE) The Department of Health is probi...,<geotext.geotext.GeoText object at 0x000002193...,[],"[Philippines – At least 53 prisoners from the,..."