In [1]:
import pandas as pd
import ast

In [2]:
df = pd.read_csv('raw_parsed_data_articles.csv')

In [3]:
df

,author,category,date,source_id,source_name,text,title,LDA_Topics,count_docs,PH_Loc,bigrams,trigrams
0,"Shaun Tandon and Arthur MacMillan, Agence Fran...",nCov,2020-02-22,NaN,NaN,Medical staff members preparing equipment to m...,Russia-linked disinformation campaign fueling ...,"['\r\n ', 'russian', 'said', 'disinformation',...","['19 outbreak', '2,340 people', '72 hours', '2...",['asia'],"[('Medical', 'staff'), ('staff', 'members'), (...","[('Medical', 'staff', 'members'), ('staff', 'm..."
1,Agence France-Presse,nCov,2020-02-22,NaN,NaN,Iranian women wearing protective masks to prev...,Iran reports 1 death among 10 new COVID-19 cases,"['\r\n ', 'iran', 'qom', 'cases', 'said', 'dea...","['1 more', '10 new', '5 and', '10 new', '8 of'...",[],"[('Iranian', 'women'), ('women', 'wearing'), (...","[('Iranian', 'women', 'wearing'), ('women', 'w..."
2,Reuters,nCov,2020-02-22,NaN,NaN,People wear masks at a main shopping area as t...,Chinese provincial gov’t: COVID-19 incubation ...,"['government', 'china', 'virus', 'hubei', 'cor...","['27 days', '14 days', '2,000 people', '24 dro...",[],"[('People', 'wear'), ('wear', 'masks'), ('mask...","[('People', 'wear', 'masks'), ('wear', 'masks'..."
3,Reuters,nCov,2020-02-22,NaN,NaN,Medical workers in protective suits inspect a ...,China brings in 7 cruise ships to house Wuhan ...,"['\r\n ', 'ships', 'china', 'workers', 'corona...","['7 cruise', '7 ships', '1,469 beds', '1,716 h...",[],"[('Medical', 'workers'), ('workers', 'protecti...","[('Medical', 'workers', 'protective'), ('worke..."
4,"Lidia Kelly, Reuters",nCov,2020-02-22,NaN,NaN,People wearing face masks walk on Bourke Stree...,Australia reopens doors to some Chinese studen...,"['\r\n ', 'students', 'australia', 'chinese', ...","['760 Chinese', '40 percent', '10 percent', '3...",[],"[('People', 'wearing'), ('wearing', 'face'), (...","[('People', 'wearing', 'face'), ('wearing', 'f..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1998,Janella Paris,nCov,2020-01-29,NaN,NaN,\nTHERMAL SCAN. The Bureau of Quarantine monit...,Man monitored for novel coronavirus dies of pn...,"['said', '\n ', 'doh', '2019-ncov', 'january',...","['2020 amid', '2019 nCoV', '6,000 in', '130 in...","['lopez', 'manila']","[('THERMAL', 'SCAN'), ('SCAN', '.'), ('.', 'Th...","[('THERMAL', 'SCAN', '.'), ('SCAN', '.', 'The'..."
1999,Rappler.com,nCov,2020-01-29,NaN,NaN,"\n \nMANILA, Philippines – The House of Repres...",LIVE: House question hour with health chief Du...,"['\n ', 'wednesday', 'january', 'session', 'co...","['2019 nCov', '3 pm', '2019 nCoV', '106 people...",[],"[('MANILA', ','), (',', 'Philippines'), ('Phil...","[('MANILA', ',', 'Philippines'), (',', 'Philip..."
2000,Randy V. Datu,nCov,2020-01-28,NaN,NaN,\nPROTEST. Residents and local leaders ask the...,This is why a cruise ship from China couldn't ...,"['\n ', 'subic', 'cruise', 'sbma', 'ships', 'f...","['778 passengers', '28 letter', '106 and', '20...","['subic', 'olongapo', 'manila']","[('PROTEST', '.'), ('.', 'Residents'), ('Resid...","[('PROTEST', '.', 'Residents'), ('.', 'Residen..."
2001,Boy Ryan B. Zabal,nCov,2020-01-28,NaN,NaN,\nPRECAUTION. The Provincial Health Office of ...,11 Chinese tourists in Aklan under observation...,"['\n ', 'health', 'chinese', 'coronavirus', 'j...","['7 adults', '4 children', '11 Chinese', '60 m...",['manila'],"[('PRECAUTION', '.'), ('.', 'The'), ('The', 'P...","[('PRECAUTION', '.', 'The'), ('.', 'The', 'Pro..."
2002,Rappler.com,nCov,2020-01-28,NaN,NaN,\n \nClaim: A screenshot of a text message tha...,"FALSE: Chinese patient in Alabang clinic, hosp...","['\n ', 'alabang', 'coronavirus', 'positive', ...","['2019 nCoV', '2019 nCoV', '4 Facebook', '2019...",['makati'],"[('Claim', ':'), (':', 'A'), ('A', 'screenshot...","[('Claim', ':', 'A'), (':', 'A', 'screenshot')..."

# Most Common Word paired with numbers on COVID articles

In [55]:
flat_list = []
for sublist in df['count_docs']:
    for item in ast.literal_eval(sublist):
        flat_list.append(item)

In [56]:
pd.Series([word.split(' ')[-1] for word in flat_list]).value_counts().head(60)

people         1175
percent         932
novel           560
million         490
cases           468
and             450
days            420
to              364
in              355
billion         330
confirmed       296
Filipinos       241
of              241
countries       235
patients        234
new             231
passengers      172
deaths          158
nCoV            154
have            152
on              124
hours           112
as              109
from            106
other           101
more            100
years            99
are              99
were             95
Chinese          89
others           88
outbreak         82
persons          70
Novel            68
coronavirus      67
a                67
lives            64
after            60
points           60
infections       58
Filipino         58
or               56
months           49
PUIs             45
is               45
who              44
pm               44
weeks            44
that             43
for              40
with             40
virus            39
crew             37
beds             37
was              36
miles            35
at               34
reported         33
shows            32
infected         32
dtype: int64

# Most common numerical phrases

In [43]:
pd.Series(flat_list).value_counts().head(50)

2019 novel          551
14 days             269
2019 nCoV           153
3 confirmed          88
2019 Novel           68
11 million           64
19 outbreak          59
19 cases             57
5 million            50
10 days              50
24 hours             49
3 percent            46
5 percent            44
1 percent            42
6 percent            39
2 percent            37
25 countries         37
9 percent            36
1 in                 35
3,700 passengers     34
4 percent            34
20 countries         33
19 and               32
19 coronavirus       30
50 percent           29
48 hours             29
5 billion            28
800 people           28
50 million           28
7 percent            27
2020 shows           27
90 percent           27
30 Filipinos         26
19 in                26
200 people           25
10 percent           24
8 billion            24
2 to                 23
300 people           23
8 percent            22
500 people           22
10,000 people        22
19 virus             21
1\n\n\n\nThere       21
19 epidemic          21
17 percent           21
2 in                 21
2019 coronavirus     21
80,000 people        21
56 million           20
dtype: int64

# Most common Bigrams

In [44]:
flat_list = []
for sublist in df['bigrams']:
    for item in ast.literal_eval(sublist):
        flat_list.append(item)

In [51]:
pd.Series(flat_list).value_counts().head(60)

(., The)                   4715
(,, ”)                     3246
(., “)                     3222
(said, .)                  2048
(novel, coronavirus)       1812
(Hong, Kong)               1301
(China, ,)                 1283
(., ``)                    1062
(”, said)                  1053
(,, '')                    1033
(,, said)                   931
(., In)                     855
(Tags, :)                   848
(:, ncov)                   847
(China, .)                  839
(,, 2020)                   839
(Wuhan, ,)                  838
(., ()                      831
(), ,)                      803
(,, China)                  775
(,, including)              685
(Department, Health)        658
(coronavirus, ,)            644
(virus, .)                  638
(., But)                    630
(new, coronavirus)          630
(confirmed, cases)          626
(., It)                     622
(), .)                      621
(2020, .)                   615
(virus, ,)                  612
(added, .)                  607
(World, Health)             596
(China, ’)                  592
(., He)                     579
(“, We)                     576
(Health, Organization)      576
(cruise, ship)              558
(., Tags)                   553
(2019, novel)               550
(., A)                      534
(South, Korea)              527
(tested, positive)          522
(BULLETIN, ))               515
(Hubei, province)           511
(coronavirus, .)            487
(., –)                      484
(coronavirus, outbreak)     481
(MANILA, BULLETIN)          456
(“, The)                    447
(,, according)              437
(,, February)               436
(Diamond, Princess)         430
((, 2019-nCoV)              423
(outbreak, .)               420
(,, Philippines)            416
(,, January)                409
(travel, ban)               397
(–, Rappler.com)            395
(mainland, China)           394
dtype: int64

# Most common Trigrams

In [52]:
flat_list = []
for sublist in df['trigrams']:
    for item in ast.literal_eval(sublist):
        flat_list.append(item)

In [53]:
pd.Series(flat_list).value_counts().head(60)

(,, ”, said)                         1025
(Tags, :, ncov)                       847
(World, Health, Organization)         575
(,, 2020, .)                          570
(., Tags, :)                          553
(2019, novel, coronavirus)            527
(”, said, .)                          525
(., “, We)                            484
(MANILA, BULLETIN, ))                 392
(., “, The)                           377
(/, MANILA, BULLETIN)                 375
(Department, Health, ()               359
(., –, Rappler.com)                   350
(said, ., “)                          347
(,, ”, added)                         337
(novel, coronavirus, ()               329
(Hong, Kong, ,)                       312
(”, added, .)                         312
((, DOH, ))                           305
(Health, (, DOH)                      299
(said, ., The)                        292
(,, Hong, Kong)                       281
(,, '', said)                         277
(Wuhan, ,, China)                     273
(acute, respiratory, disease)         272
((, 2019-nCoV, ))                     263
(,, China, ,)                         259
(,, Philippines, –)                   257
(MANILA, ,, Philippines)              246
((, WHO, ))                           245
((, READ, :)                          239
(READ, MORE, :)                       233
(coronavirus, (, 2019-nCoV)           230
(., (, READ)                          230
(coronavirus, acute, respiratory)     229
(Health, Organization, ()             229
(Secretary, Francisco, Duque)         228
(Organization, (, WHO)                226
(By, Agence, France-Presse)           219
(2020, ., ()                          217
(novel, coronavirus, .)               211
(., READ, MORE)                       210
(., “, I)                             207
(Lunar, New, Year)                    206
(Hubei, province, ,)                  205
(novel, coronavirus, acute)           202
(respiratory, disease, ()             199
(The, World, Health)                  192
(Health, Secretary, Francisco)        186
(novel, coronavirus, ,)               182
(coronavirus, disease, 2019)          176
(New, Clark, City)                    174
(Francisco, Duque, III)               174
(., Meanwhile, ,)                     172
(., He, said)                         171
(,, however, ,)                       162
(2019-nCoV, ARD, ))                   161
((, 2019-nCoV, ARD)                   160
(Department, Foreign, Affairs)        155
(., ``, We)                           155
dtype: int64